# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/f/cppgames/GameEngine2020

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/f/cppgames/GameEngine2020

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/cppgames/GameEngine2020/CMakeFiles /mnt/f/cppgames/GameEngine2020/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/cppgames/GameEngine2020/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameEngine2020

# Build rule for target.
GameEngine2020: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GameEngine2020
.PHONY : GameEngine2020

# fast build rule for target.
GameEngine2020/fast:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/build
.PHONY : GameEngine2020/fast

src/Source_Files/Actor/Actor.o: src/Source_Files/Actor/Actor.cpp.o

.PHONY : src/Source_Files/Actor/Actor.o

# target to build an object file
src/Source_Files/Actor/Actor.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Actor.cpp.o
.PHONY : src/Source_Files/Actor/Actor.cpp.o

src/Source_Files/Actor/Actor.i: src/Source_Files/Actor/Actor.cpp.i

.PHONY : src/Source_Files/Actor/Actor.i

# target to preprocess a source file
src/Source_Files/Actor/Actor.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Actor.cpp.i
.PHONY : src/Source_Files/Actor/Actor.cpp.i

src/Source_Files/Actor/Actor.s: src/Source_Files/Actor/Actor.cpp.s

.PHONY : src/Source_Files/Actor/Actor.s

# target to generate assembly for a file
src/Source_Files/Actor/Actor.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Actor.cpp.s
.PHONY : src/Source_Files/Actor/Actor.cpp.s

src/Source_Files/Actor/Camera.o: src/Source_Files/Actor/Camera.cpp.o

.PHONY : src/Source_Files/Actor/Camera.o

# target to build an object file
src/Source_Files/Actor/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Camera.cpp.o
.PHONY : src/Source_Files/Actor/Camera.cpp.o

src/Source_Files/Actor/Camera.i: src/Source_Files/Actor/Camera.cpp.i

.PHONY : src/Source_Files/Actor/Camera.i

# target to preprocess a source file
src/Source_Files/Actor/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Camera.cpp.i
.PHONY : src/Source_Files/Actor/Camera.cpp.i

src/Source_Files/Actor/Camera.s: src/Source_Files/Actor/Camera.cpp.s

.PHONY : src/Source_Files/Actor/Camera.s

# target to generate assembly for a file
src/Source_Files/Actor/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Camera.cpp.s
.PHONY : src/Source_Files/Actor/Camera.cpp.s

src/Source_Files/Actor/Player.o: src/Source_Files/Actor/Player.cpp.o

.PHONY : src/Source_Files/Actor/Player.o

# target to build an object file
src/Source_Files/Actor/Player.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Player.cpp.o
.PHONY : src/Source_Files/Actor/Player.cpp.o

src/Source_Files/Actor/Player.i: src/Source_Files/Actor/Player.cpp.i

.PHONY : src/Source_Files/Actor/Player.i

# target to preprocess a source file
src/Source_Files/Actor/Player.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Player.cpp.i
.PHONY : src/Source_Files/Actor/Player.cpp.i

src/Source_Files/Actor/Player.s: src/Source_Files/Actor/Player.cpp.s

.PHONY : src/Source_Files/Actor/Player.s

# target to generate assembly for a file
src/Source_Files/Actor/Player.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Actor/Player.cpp.s
.PHONY : src/Source_Files/Actor/Player.cpp.s

src/Source_Files/Behavior/ActionState/ActionStateMap.o: src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.o

.PHONY : src/Source_Files/Behavior/ActionState/ActionStateMap.o

# target to build an object file
src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.o
.PHONY : src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.o

src/Source_Files/Behavior/ActionState/ActionStateMap.i: src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.i

.PHONY : src/Source_Files/Behavior/ActionState/ActionStateMap.i

# target to preprocess a source file
src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.i
.PHONY : src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.i

src/Source_Files/Behavior/ActionState/ActionStateMap.s: src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.s

.PHONY : src/Source_Files/Behavior/ActionState/ActionStateMap.s

# target to generate assembly for a file
src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.s
.PHONY : src/Source_Files/Behavior/ActionState/ActionStateMap.cpp.s

src/Source_Files/Behavior/ActionState/PlayerAirborneState.o: src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.o

.PHONY : src/Source_Files/Behavior/ActionState/PlayerAirborneState.o

# target to build an object file
src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.o
.PHONY : src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.o

src/Source_Files/Behavior/ActionState/PlayerAirborneState.i: src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.i

.PHONY : src/Source_Files/Behavior/ActionState/PlayerAirborneState.i

# target to preprocess a source file
src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.i
.PHONY : src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.i

src/Source_Files/Behavior/ActionState/PlayerAirborneState.s: src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.s

.PHONY : src/Source_Files/Behavior/ActionState/PlayerAirborneState.s

# target to generate assembly for a file
src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.s
.PHONY : src/Source_Files/Behavior/ActionState/PlayerAirborneState.cpp.s

src/Source_Files/Behavior/ActionState/PlayerIdleState.o: src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.o

.PHONY : src/Source_Files/Behavior/ActionState/PlayerIdleState.o

# target to build an object file
src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.o
.PHONY : src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.o

src/Source_Files/Behavior/ActionState/PlayerIdleState.i: src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.i

.PHONY : src/Source_Files/Behavior/ActionState/PlayerIdleState.i

# target to preprocess a source file
src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.i
.PHONY : src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.i

src/Source_Files/Behavior/ActionState/PlayerIdleState.s: src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.s

.PHONY : src/Source_Files/Behavior/ActionState/PlayerIdleState.s

# target to generate assembly for a file
src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.s
.PHONY : src/Source_Files/Behavior/ActionState/PlayerIdleState.cpp.s

src/Source_Files/Behavior/ActionState/PlayerJumpState.o: src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.o

.PHONY : src/Source_Files/Behavior/ActionState/PlayerJumpState.o

# target to build an object file
src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.o
.PHONY : src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.o

src/Source_Files/Behavior/ActionState/PlayerJumpState.i: src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.i

.PHONY : src/Source_Files/Behavior/ActionState/PlayerJumpState.i

# target to preprocess a source file
src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.i
.PHONY : src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.i

src/Source_Files/Behavior/ActionState/PlayerJumpState.s: src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.s

.PHONY : src/Source_Files/Behavior/ActionState/PlayerJumpState.s

# target to generate assembly for a file
src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.s
.PHONY : src/Source_Files/Behavior/ActionState/PlayerJumpState.cpp.s

src/Source_Files/Behavior/ActionState/PlayerMoveState.o: src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.o

.PHONY : src/Source_Files/Behavior/ActionState/PlayerMoveState.o

# target to build an object file
src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.o
.PHONY : src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.o

src/Source_Files/Behavior/ActionState/PlayerMoveState.i: src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.i

.PHONY : src/Source_Files/Behavior/ActionState/PlayerMoveState.i

# target to preprocess a source file
src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.i
.PHONY : src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.i

src/Source_Files/Behavior/ActionState/PlayerMoveState.s: src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.s

.PHONY : src/Source_Files/Behavior/ActionState/PlayerMoveState.s

# target to generate assembly for a file
src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.s
.PHONY : src/Source_Files/Behavior/ActionState/PlayerMoveState.cpp.s

src/Source_Files/Behavior/ActionState/PlayerRunState.o: src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.o

.PHONY : src/Source_Files/Behavior/ActionState/PlayerRunState.o

# target to build an object file
src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.o
.PHONY : src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.o

src/Source_Files/Behavior/ActionState/PlayerRunState.i: src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.i

.PHONY : src/Source_Files/Behavior/ActionState/PlayerRunState.i

# target to preprocess a source file
src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.i
.PHONY : src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.i

src/Source_Files/Behavior/ActionState/PlayerRunState.s: src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.s

.PHONY : src/Source_Files/Behavior/ActionState/PlayerRunState.s

# target to generate assembly for a file
src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.s
.PHONY : src/Source_Files/Behavior/ActionState/PlayerRunState.cpp.s

src/Source_Files/Behavior/Animator.o: src/Source_Files/Behavior/Animator.cpp.o

.PHONY : src/Source_Files/Behavior/Animator.o

# target to build an object file
src/Source_Files/Behavior/Animator.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/Animator.cpp.o
.PHONY : src/Source_Files/Behavior/Animator.cpp.o

src/Source_Files/Behavior/Animator.i: src/Source_Files/Behavior/Animator.cpp.i

.PHONY : src/Source_Files/Behavior/Animator.i

# target to preprocess a source file
src/Source_Files/Behavior/Animator.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/Animator.cpp.i
.PHONY : src/Source_Files/Behavior/Animator.cpp.i

src/Source_Files/Behavior/Animator.s: src/Source_Files/Behavior/Animator.cpp.s

.PHONY : src/Source_Files/Behavior/Animator.s

# target to generate assembly for a file
src/Source_Files/Behavior/Animator.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/Animator.cpp.s
.PHONY : src/Source_Files/Behavior/Animator.cpp.s

src/Source_Files/Behavior/Behavior.o: src/Source_Files/Behavior/Behavior.cpp.o

.PHONY : src/Source_Files/Behavior/Behavior.o

# target to build an object file
src/Source_Files/Behavior/Behavior.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/Behavior.cpp.o
.PHONY : src/Source_Files/Behavior/Behavior.cpp.o

src/Source_Files/Behavior/Behavior.i: src/Source_Files/Behavior/Behavior.cpp.i

.PHONY : src/Source_Files/Behavior/Behavior.i

# target to preprocess a source file
src/Source_Files/Behavior/Behavior.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/Behavior.cpp.i
.PHONY : src/Source_Files/Behavior/Behavior.cpp.i

src/Source_Files/Behavior/Behavior.s: src/Source_Files/Behavior/Behavior.cpp.s

.PHONY : src/Source_Files/Behavior/Behavior.s

# target to generate assembly for a file
src/Source_Files/Behavior/Behavior.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/Behavior.cpp.s
.PHONY : src/Source_Files/Behavior/Behavior.cpp.s

src/Source_Files/Behavior/GameTransform.o: src/Source_Files/Behavior/GameTransform.cpp.o

.PHONY : src/Source_Files/Behavior/GameTransform.o

# target to build an object file
src/Source_Files/Behavior/GameTransform.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/GameTransform.cpp.o
.PHONY : src/Source_Files/Behavior/GameTransform.cpp.o

src/Source_Files/Behavior/GameTransform.i: src/Source_Files/Behavior/GameTransform.cpp.i

.PHONY : src/Source_Files/Behavior/GameTransform.i

# target to preprocess a source file
src/Source_Files/Behavior/GameTransform.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/GameTransform.cpp.i
.PHONY : src/Source_Files/Behavior/GameTransform.cpp.i

src/Source_Files/Behavior/GameTransform.s: src/Source_Files/Behavior/GameTransform.cpp.s

.PHONY : src/Source_Files/Behavior/GameTransform.s

# target to generate assembly for a file
src/Source_Files/Behavior/GameTransform.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/GameTransform.cpp.s
.PHONY : src/Source_Files/Behavior/GameTransform.cpp.s

src/Source_Files/Behavior/PhysEventHandler.o: src/Source_Files/Behavior/PhysEventHandler.cpp.o

.PHONY : src/Source_Files/Behavior/PhysEventHandler.o

# target to build an object file
src/Source_Files/Behavior/PhysEventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/PhysEventHandler.cpp.o
.PHONY : src/Source_Files/Behavior/PhysEventHandler.cpp.o

src/Source_Files/Behavior/PhysEventHandler.i: src/Source_Files/Behavior/PhysEventHandler.cpp.i

.PHONY : src/Source_Files/Behavior/PhysEventHandler.i

# target to preprocess a source file
src/Source_Files/Behavior/PhysEventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/PhysEventHandler.cpp.i
.PHONY : src/Source_Files/Behavior/PhysEventHandler.cpp.i

src/Source_Files/Behavior/PhysEventHandler.s: src/Source_Files/Behavior/PhysEventHandler.cpp.s

.PHONY : src/Source_Files/Behavior/PhysEventHandler.s

# target to generate assembly for a file
src/Source_Files/Behavior/PhysEventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Behavior/PhysEventHandler.cpp.s
.PHONY : src/Source_Files/Behavior/PhysEventHandler.cpp.s

src/Source_Files/GUI/Button.o: src/Source_Files/GUI/Button.cpp.o

.PHONY : src/Source_Files/GUI/Button.o

# target to build an object file
src/Source_Files/GUI/Button.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/Button.cpp.o
.PHONY : src/Source_Files/GUI/Button.cpp.o

src/Source_Files/GUI/Button.i: src/Source_Files/GUI/Button.cpp.i

.PHONY : src/Source_Files/GUI/Button.i

# target to preprocess a source file
src/Source_Files/GUI/Button.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/Button.cpp.i
.PHONY : src/Source_Files/GUI/Button.cpp.i

src/Source_Files/GUI/Button.s: src/Source_Files/GUI/Button.cpp.s

.PHONY : src/Source_Files/GUI/Button.s

# target to generate assembly for a file
src/Source_Files/GUI/Button.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/Button.cpp.s
.PHONY : src/Source_Files/GUI/Button.cpp.s

src/Source_Files/GUI/MenuButton.o: src/Source_Files/GUI/MenuButton.cpp.o

.PHONY : src/Source_Files/GUI/MenuButton.o

# target to build an object file
src/Source_Files/GUI/MenuButton.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/MenuButton.cpp.o
.PHONY : src/Source_Files/GUI/MenuButton.cpp.o

src/Source_Files/GUI/MenuButton.i: src/Source_Files/GUI/MenuButton.cpp.i

.PHONY : src/Source_Files/GUI/MenuButton.i

# target to preprocess a source file
src/Source_Files/GUI/MenuButton.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/MenuButton.cpp.i
.PHONY : src/Source_Files/GUI/MenuButton.cpp.i

src/Source_Files/GUI/MenuButton.s: src/Source_Files/GUI/MenuButton.cpp.s

.PHONY : src/Source_Files/GUI/MenuButton.s

# target to generate assembly for a file
src/Source_Files/GUI/MenuButton.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/MenuButton.cpp.s
.PHONY : src/Source_Files/GUI/MenuButton.cpp.s

src/Source_Files/GUI/Widget.o: src/Source_Files/GUI/Widget.cpp.o

.PHONY : src/Source_Files/GUI/Widget.o

# target to build an object file
src/Source_Files/GUI/Widget.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/Widget.cpp.o
.PHONY : src/Source_Files/GUI/Widget.cpp.o

src/Source_Files/GUI/Widget.i: src/Source_Files/GUI/Widget.cpp.i

.PHONY : src/Source_Files/GUI/Widget.i

# target to preprocess a source file
src/Source_Files/GUI/Widget.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/Widget.cpp.i
.PHONY : src/Source_Files/GUI/Widget.cpp.i

src/Source_Files/GUI/Widget.s: src/Source_Files/GUI/Widget.cpp.s

.PHONY : src/Source_Files/GUI/Widget.s

# target to generate assembly for a file
src/Source_Files/GUI/Widget.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GUI/Widget.cpp.s
.PHONY : src/Source_Files/GUI/Widget.cpp.s

src/Source_Files/GameEngine2020.o: src/Source_Files/GameEngine2020.cpp.o

.PHONY : src/Source_Files/GameEngine2020.o

# target to build an object file
src/Source_Files/GameEngine2020.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GameEngine2020.cpp.o
.PHONY : src/Source_Files/GameEngine2020.cpp.o

src/Source_Files/GameEngine2020.i: src/Source_Files/GameEngine2020.cpp.i

.PHONY : src/Source_Files/GameEngine2020.i

# target to preprocess a source file
src/Source_Files/GameEngine2020.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GameEngine2020.cpp.i
.PHONY : src/Source_Files/GameEngine2020.cpp.i

src/Source_Files/GameEngine2020.s: src/Source_Files/GameEngine2020.cpp.s

.PHONY : src/Source_Files/GameEngine2020.s

# target to generate assembly for a file
src/Source_Files/GameEngine2020.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/GameEngine2020.cpp.s
.PHONY : src/Source_Files/GameEngine2020.cpp.s

src/Source_Files/Graphics/Animation.o: src/Source_Files/Graphics/Animation.cpp.o

.PHONY : src/Source_Files/Graphics/Animation.o

# target to build an object file
src/Source_Files/Graphics/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Graphics/Animation.cpp.o
.PHONY : src/Source_Files/Graphics/Animation.cpp.o

src/Source_Files/Graphics/Animation.i: src/Source_Files/Graphics/Animation.cpp.i

.PHONY : src/Source_Files/Graphics/Animation.i

# target to preprocess a source file
src/Source_Files/Graphics/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Graphics/Animation.cpp.i
.PHONY : src/Source_Files/Graphics/Animation.cpp.i

src/Source_Files/Graphics/Animation.s: src/Source_Files/Graphics/Animation.cpp.s

.PHONY : src/Source_Files/Graphics/Animation.s

# target to generate assembly for a file
src/Source_Files/Graphics/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Graphics/Animation.cpp.s
.PHONY : src/Source_Files/Graphics/Animation.cpp.s

src/Source_Files/Graphics/Renderer.o: src/Source_Files/Graphics/Renderer.cpp.o

.PHONY : src/Source_Files/Graphics/Renderer.o

# target to build an object file
src/Source_Files/Graphics/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Graphics/Renderer.cpp.o
.PHONY : src/Source_Files/Graphics/Renderer.cpp.o

src/Source_Files/Graphics/Renderer.i: src/Source_Files/Graphics/Renderer.cpp.i

.PHONY : src/Source_Files/Graphics/Renderer.i

# target to preprocess a source file
src/Source_Files/Graphics/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Graphics/Renderer.cpp.i
.PHONY : src/Source_Files/Graphics/Renderer.cpp.i

src/Source_Files/Graphics/Renderer.s: src/Source_Files/Graphics/Renderer.cpp.s

.PHONY : src/Source_Files/Graphics/Renderer.s

# target to generate assembly for a file
src/Source_Files/Graphics/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Graphics/Renderer.cpp.s
.PHONY : src/Source_Files/Graphics/Renderer.cpp.s

src/Source_Files/Level/Level.o: src/Source_Files/Level/Level.cpp.o

.PHONY : src/Source_Files/Level/Level.o

# target to build an object file
src/Source_Files/Level/Level.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Level/Level.cpp.o
.PHONY : src/Source_Files/Level/Level.cpp.o

src/Source_Files/Level/Level.i: src/Source_Files/Level/Level.cpp.i

.PHONY : src/Source_Files/Level/Level.i

# target to preprocess a source file
src/Source_Files/Level/Level.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Level/Level.cpp.i
.PHONY : src/Source_Files/Level/Level.cpp.i

src/Source_Files/Level/Level.s: src/Source_Files/Level/Level.cpp.s

.PHONY : src/Source_Files/Level/Level.s

# target to generate assembly for a file
src/Source_Files/Level/Level.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Level/Level.cpp.s
.PHONY : src/Source_Files/Level/Level.cpp.s

src/Source_Files/Physics/Bodies/PhysicsBody.o: src/Source_Files/Physics/Bodies/PhysicsBody.cpp.o

.PHONY : src/Source_Files/Physics/Bodies/PhysicsBody.o

# target to build an object file
src/Source_Files/Physics/Bodies/PhysicsBody.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/Bodies/PhysicsBody.cpp.o
.PHONY : src/Source_Files/Physics/Bodies/PhysicsBody.cpp.o

src/Source_Files/Physics/Bodies/PhysicsBody.i: src/Source_Files/Physics/Bodies/PhysicsBody.cpp.i

.PHONY : src/Source_Files/Physics/Bodies/PhysicsBody.i

# target to preprocess a source file
src/Source_Files/Physics/Bodies/PhysicsBody.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/Bodies/PhysicsBody.cpp.i
.PHONY : src/Source_Files/Physics/Bodies/PhysicsBody.cpp.i

src/Source_Files/Physics/Bodies/PhysicsBody.s: src/Source_Files/Physics/Bodies/PhysicsBody.cpp.s

.PHONY : src/Source_Files/Physics/Bodies/PhysicsBody.s

# target to generate assembly for a file
src/Source_Files/Physics/Bodies/PhysicsBody.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/Bodies/PhysicsBody.cpp.s
.PHONY : src/Source_Files/Physics/Bodies/PhysicsBody.cpp.s

src/Source_Files/Physics/ColPair.o: src/Source_Files/Physics/ColPair.cpp.o

.PHONY : src/Source_Files/Physics/ColPair.o

# target to build an object file
src/Source_Files/Physics/ColPair.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/ColPair.cpp.o
.PHONY : src/Source_Files/Physics/ColPair.cpp.o

src/Source_Files/Physics/ColPair.i: src/Source_Files/Physics/ColPair.cpp.i

.PHONY : src/Source_Files/Physics/ColPair.i

# target to preprocess a source file
src/Source_Files/Physics/ColPair.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/ColPair.cpp.i
.PHONY : src/Source_Files/Physics/ColPair.cpp.i

src/Source_Files/Physics/ColPair.s: src/Source_Files/Physics/ColPair.cpp.s

.PHONY : src/Source_Files/Physics/ColPair.s

# target to generate assembly for a file
src/Source_Files/Physics/ColPair.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/ColPair.cpp.s
.PHONY : src/Source_Files/Physics/ColPair.cpp.s

src/Source_Files/Physics/CollisionEvent.o: src/Source_Files/Physics/CollisionEvent.cpp.o

.PHONY : src/Source_Files/Physics/CollisionEvent.o

# target to build an object file
src/Source_Files/Physics/CollisionEvent.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/CollisionEvent.cpp.o
.PHONY : src/Source_Files/Physics/CollisionEvent.cpp.o

src/Source_Files/Physics/CollisionEvent.i: src/Source_Files/Physics/CollisionEvent.cpp.i

.PHONY : src/Source_Files/Physics/CollisionEvent.i

# target to preprocess a source file
src/Source_Files/Physics/CollisionEvent.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/CollisionEvent.cpp.i
.PHONY : src/Source_Files/Physics/CollisionEvent.cpp.i

src/Source_Files/Physics/CollisionEvent.s: src/Source_Files/Physics/CollisionEvent.cpp.s

.PHONY : src/Source_Files/Physics/CollisionEvent.s

# target to generate assembly for a file
src/Source_Files/Physics/CollisionEvent.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/CollisionEvent.cpp.s
.PHONY : src/Source_Files/Physics/CollisionEvent.cpp.s

src/Source_Files/Physics/PhysMath.o: src/Source_Files/Physics/PhysMath.cpp.o

.PHONY : src/Source_Files/Physics/PhysMath.o

# target to build an object file
src/Source_Files/Physics/PhysMath.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/PhysMath.cpp.o
.PHONY : src/Source_Files/Physics/PhysMath.cpp.o

src/Source_Files/Physics/PhysMath.i: src/Source_Files/Physics/PhysMath.cpp.i

.PHONY : src/Source_Files/Physics/PhysMath.i

# target to preprocess a source file
src/Source_Files/Physics/PhysMath.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/PhysMath.cpp.i
.PHONY : src/Source_Files/Physics/PhysMath.cpp.i

src/Source_Files/Physics/PhysMath.s: src/Source_Files/Physics/PhysMath.cpp.s

.PHONY : src/Source_Files/Physics/PhysMath.s

# target to generate assembly for a file
src/Source_Files/Physics/PhysMath.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/PhysMath.cpp.s
.PHONY : src/Source_Files/Physics/PhysMath.cpp.s

src/Source_Files/Physics/PhysicsEngine.o: src/Source_Files/Physics/PhysicsEngine.cpp.o

.PHONY : src/Source_Files/Physics/PhysicsEngine.o

# target to build an object file
src/Source_Files/Physics/PhysicsEngine.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/PhysicsEngine.cpp.o
.PHONY : src/Source_Files/Physics/PhysicsEngine.cpp.o

src/Source_Files/Physics/PhysicsEngine.i: src/Source_Files/Physics/PhysicsEngine.cpp.i

.PHONY : src/Source_Files/Physics/PhysicsEngine.i

# target to preprocess a source file
src/Source_Files/Physics/PhysicsEngine.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/PhysicsEngine.cpp.i
.PHONY : src/Source_Files/Physics/PhysicsEngine.cpp.i

src/Source_Files/Physics/PhysicsEngine.s: src/Source_Files/Physics/PhysicsEngine.cpp.s

.PHONY : src/Source_Files/Physics/PhysicsEngine.s

# target to generate assembly for a file
src/Source_Files/Physics/PhysicsEngine.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/PhysicsEngine.cpp.s
.PHONY : src/Source_Files/Physics/PhysicsEngine.cpp.s

src/Source_Files/Physics/SweepAndPrune.o: src/Source_Files/Physics/SweepAndPrune.cpp.o

.PHONY : src/Source_Files/Physics/SweepAndPrune.o

# target to build an object file
src/Source_Files/Physics/SweepAndPrune.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/SweepAndPrune.cpp.o
.PHONY : src/Source_Files/Physics/SweepAndPrune.cpp.o

src/Source_Files/Physics/SweepAndPrune.i: src/Source_Files/Physics/SweepAndPrune.cpp.i

.PHONY : src/Source_Files/Physics/SweepAndPrune.i

# target to preprocess a source file
src/Source_Files/Physics/SweepAndPrune.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/SweepAndPrune.cpp.i
.PHONY : src/Source_Files/Physics/SweepAndPrune.cpp.i

src/Source_Files/Physics/SweepAndPrune.s: src/Source_Files/Physics/SweepAndPrune.cpp.s

.PHONY : src/Source_Files/Physics/SweepAndPrune.s

# target to generate assembly for a file
src/Source_Files/Physics/SweepAndPrune.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Physics/SweepAndPrune.cpp.s
.PHONY : src/Source_Files/Physics/SweepAndPrune.cpp.s

src/Source_Files/Space2D/AffineMatrix.o: src/Source_Files/Space2D/AffineMatrix.cpp.o

.PHONY : src/Source_Files/Space2D/AffineMatrix.o

# target to build an object file
src/Source_Files/Space2D/AffineMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/AffineMatrix.cpp.o
.PHONY : src/Source_Files/Space2D/AffineMatrix.cpp.o

src/Source_Files/Space2D/AffineMatrix.i: src/Source_Files/Space2D/AffineMatrix.cpp.i

.PHONY : src/Source_Files/Space2D/AffineMatrix.i

# target to preprocess a source file
src/Source_Files/Space2D/AffineMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/AffineMatrix.cpp.i
.PHONY : src/Source_Files/Space2D/AffineMatrix.cpp.i

src/Source_Files/Space2D/AffineMatrix.s: src/Source_Files/Space2D/AffineMatrix.cpp.s

.PHONY : src/Source_Files/Space2D/AffineMatrix.s

# target to generate assembly for a file
src/Source_Files/Space2D/AffineMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/AffineMatrix.cpp.s
.PHONY : src/Source_Files/Space2D/AffineMatrix.cpp.s

src/Source_Files/Space2D/AngularType.o: src/Source_Files/Space2D/AngularType.cpp.o

.PHONY : src/Source_Files/Space2D/AngularType.o

# target to build an object file
src/Source_Files/Space2D/AngularType.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/AngularType.cpp.o
.PHONY : src/Source_Files/Space2D/AngularType.cpp.o

src/Source_Files/Space2D/AngularType.i: src/Source_Files/Space2D/AngularType.cpp.i

.PHONY : src/Source_Files/Space2D/AngularType.i

# target to preprocess a source file
src/Source_Files/Space2D/AngularType.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/AngularType.cpp.i
.PHONY : src/Source_Files/Space2D/AngularType.cpp.i

src/Source_Files/Space2D/AngularType.s: src/Source_Files/Space2D/AngularType.cpp.s

.PHONY : src/Source_Files/Space2D/AngularType.s

# target to generate assembly for a file
src/Source_Files/Space2D/AngularType.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/AngularType.cpp.s
.PHONY : src/Source_Files/Space2D/AngularType.cpp.s

src/Source_Files/Space2D/Dimension2.o: src/Source_Files/Space2D/Dimension2.cpp.o

.PHONY : src/Source_Files/Space2D/Dimension2.o

# target to build an object file
src/Source_Files/Space2D/Dimension2.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Dimension2.cpp.o
.PHONY : src/Source_Files/Space2D/Dimension2.cpp.o

src/Source_Files/Space2D/Dimension2.i: src/Source_Files/Space2D/Dimension2.cpp.i

.PHONY : src/Source_Files/Space2D/Dimension2.i

# target to preprocess a source file
src/Source_Files/Space2D/Dimension2.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Dimension2.cpp.i
.PHONY : src/Source_Files/Space2D/Dimension2.cpp.i

src/Source_Files/Space2D/Dimension2.s: src/Source_Files/Space2D/Dimension2.cpp.s

.PHONY : src/Source_Files/Space2D/Dimension2.s

# target to generate assembly for a file
src/Source_Files/Space2D/Dimension2.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Dimension2.cpp.s
.PHONY : src/Source_Files/Space2D/Dimension2.cpp.s

src/Source_Files/Space2D/NormalizedVec2.o: src/Source_Files/Space2D/NormalizedVec2.cpp.o

.PHONY : src/Source_Files/Space2D/NormalizedVec2.o

# target to build an object file
src/Source_Files/Space2D/NormalizedVec2.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/NormalizedVec2.cpp.o
.PHONY : src/Source_Files/Space2D/NormalizedVec2.cpp.o

src/Source_Files/Space2D/NormalizedVec2.i: src/Source_Files/Space2D/NormalizedVec2.cpp.i

.PHONY : src/Source_Files/Space2D/NormalizedVec2.i

# target to preprocess a source file
src/Source_Files/Space2D/NormalizedVec2.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/NormalizedVec2.cpp.i
.PHONY : src/Source_Files/Space2D/NormalizedVec2.cpp.i

src/Source_Files/Space2D/NormalizedVec2.s: src/Source_Files/Space2D/NormalizedVec2.cpp.s

.PHONY : src/Source_Files/Space2D/NormalizedVec2.s

# target to generate assembly for a file
src/Source_Files/Space2D/NormalizedVec2.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/NormalizedVec2.cpp.s
.PHONY : src/Source_Files/Space2D/NormalizedVec2.cpp.s

src/Source_Files/Space2D/Point2.o: src/Source_Files/Space2D/Point2.cpp.o

.PHONY : src/Source_Files/Space2D/Point2.o

# target to build an object file
src/Source_Files/Space2D/Point2.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Point2.cpp.o
.PHONY : src/Source_Files/Space2D/Point2.cpp.o

src/Source_Files/Space2D/Point2.i: src/Source_Files/Space2D/Point2.cpp.i

.PHONY : src/Source_Files/Space2D/Point2.i

# target to preprocess a source file
src/Source_Files/Space2D/Point2.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Point2.cpp.i
.PHONY : src/Source_Files/Space2D/Point2.cpp.i

src/Source_Files/Space2D/Point2.s: src/Source_Files/Space2D/Point2.cpp.s

.PHONY : src/Source_Files/Space2D/Point2.s

# target to generate assembly for a file
src/Source_Files/Space2D/Point2.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Point2.cpp.s
.PHONY : src/Source_Files/Space2D/Point2.cpp.s

src/Source_Files/Space2D/Poly2.o: src/Source_Files/Space2D/Poly2.cpp.o

.PHONY : src/Source_Files/Space2D/Poly2.o

# target to build an object file
src/Source_Files/Space2D/Poly2.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Poly2.cpp.o
.PHONY : src/Source_Files/Space2D/Poly2.cpp.o

src/Source_Files/Space2D/Poly2.i: src/Source_Files/Space2D/Poly2.cpp.i

.PHONY : src/Source_Files/Space2D/Poly2.i

# target to preprocess a source file
src/Source_Files/Space2D/Poly2.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Poly2.cpp.i
.PHONY : src/Source_Files/Space2D/Poly2.cpp.i

src/Source_Files/Space2D/Poly2.s: src/Source_Files/Space2D/Poly2.cpp.s

.PHONY : src/Source_Files/Space2D/Poly2.s

# target to generate assembly for a file
src/Source_Files/Space2D/Poly2.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Poly2.cpp.s
.PHONY : src/Source_Files/Space2D/Poly2.cpp.s

src/Source_Files/Space2D/Rect2.o: src/Source_Files/Space2D/Rect2.cpp.o

.PHONY : src/Source_Files/Space2D/Rect2.o

# target to build an object file
src/Source_Files/Space2D/Rect2.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Rect2.cpp.o
.PHONY : src/Source_Files/Space2D/Rect2.cpp.o

src/Source_Files/Space2D/Rect2.i: src/Source_Files/Space2D/Rect2.cpp.i

.PHONY : src/Source_Files/Space2D/Rect2.i

# target to preprocess a source file
src/Source_Files/Space2D/Rect2.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Rect2.cpp.i
.PHONY : src/Source_Files/Space2D/Rect2.cpp.i

src/Source_Files/Space2D/Rect2.s: src/Source_Files/Space2D/Rect2.cpp.s

.PHONY : src/Source_Files/Space2D/Rect2.s

# target to generate assembly for a file
src/Source_Files/Space2D/Rect2.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Rect2.cpp.s
.PHONY : src/Source_Files/Space2D/Rect2.cpp.s

src/Source_Files/Space2D/Vec2.o: src/Source_Files/Space2D/Vec2.cpp.o

.PHONY : src/Source_Files/Space2D/Vec2.o

# target to build an object file
src/Source_Files/Space2D/Vec2.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Vec2.cpp.o
.PHONY : src/Source_Files/Space2D/Vec2.cpp.o

src/Source_Files/Space2D/Vec2.i: src/Source_Files/Space2D/Vec2.cpp.i

.PHONY : src/Source_Files/Space2D/Vec2.i

# target to preprocess a source file
src/Source_Files/Space2D/Vec2.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Vec2.cpp.i
.PHONY : src/Source_Files/Space2D/Vec2.cpp.i

src/Source_Files/Space2D/Vec2.s: src/Source_Files/Space2D/Vec2.cpp.s

.PHONY : src/Source_Files/Space2D/Vec2.s

# target to generate assembly for a file
src/Source_Files/Space2D/Vec2.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Space2D/Vec2.cpp.s
.PHONY : src/Source_Files/Space2D/Vec2.cpp.s

src/Source_Files/State/GameState.o: src/Source_Files/State/GameState.cpp.o

.PHONY : src/Source_Files/State/GameState.o

# target to build an object file
src/Source_Files/State/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/GameState.cpp.o
.PHONY : src/Source_Files/State/GameState.cpp.o

src/Source_Files/State/GameState.i: src/Source_Files/State/GameState.cpp.i

.PHONY : src/Source_Files/State/GameState.i

# target to preprocess a source file
src/Source_Files/State/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/GameState.cpp.i
.PHONY : src/Source_Files/State/GameState.cpp.i

src/Source_Files/State/GameState.s: src/Source_Files/State/GameState.cpp.s

.PHONY : src/Source_Files/State/GameState.s

# target to generate assembly for a file
src/Source_Files/State/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/GameState.cpp.s
.PHONY : src/Source_Files/State/GameState.cpp.s

src/Source_Files/State/MenuState.o: src/Source_Files/State/MenuState.cpp.o

.PHONY : src/Source_Files/State/MenuState.o

# target to build an object file
src/Source_Files/State/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/MenuState.cpp.o
.PHONY : src/Source_Files/State/MenuState.cpp.o

src/Source_Files/State/MenuState.i: src/Source_Files/State/MenuState.cpp.i

.PHONY : src/Source_Files/State/MenuState.i

# target to preprocess a source file
src/Source_Files/State/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/MenuState.cpp.i
.PHONY : src/Source_Files/State/MenuState.cpp.i

src/Source_Files/State/MenuState.s: src/Source_Files/State/MenuState.cpp.s

.PHONY : src/Source_Files/State/MenuState.s

# target to generate assembly for a file
src/Source_Files/State/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/MenuState.cpp.s
.PHONY : src/Source_Files/State/MenuState.cpp.s

src/Source_Files/State/State.o: src/Source_Files/State/State.cpp.o

.PHONY : src/Source_Files/State/State.o

# target to build an object file
src/Source_Files/State/State.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/State.cpp.o
.PHONY : src/Source_Files/State/State.cpp.o

src/Source_Files/State/State.i: src/Source_Files/State/State.cpp.i

.PHONY : src/Source_Files/State/State.i

# target to preprocess a source file
src/Source_Files/State/State.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/State.cpp.i
.PHONY : src/Source_Files/State/State.cpp.i

src/Source_Files/State/State.s: src/Source_Files/State/State.cpp.s

.PHONY : src/Source_Files/State/State.s

# target to generate assembly for a file
src/Source_Files/State/State.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/State.cpp.s
.PHONY : src/Source_Files/State/State.cpp.s

src/Source_Files/State/StateManager.o: src/Source_Files/State/StateManager.cpp.o

.PHONY : src/Source_Files/State/StateManager.o

# target to build an object file
src/Source_Files/State/StateManager.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/StateManager.cpp.o
.PHONY : src/Source_Files/State/StateManager.cpp.o

src/Source_Files/State/StateManager.i: src/Source_Files/State/StateManager.cpp.i

.PHONY : src/Source_Files/State/StateManager.i

# target to preprocess a source file
src/Source_Files/State/StateManager.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/StateManager.cpp.i
.PHONY : src/Source_Files/State/StateManager.cpp.i

src/Source_Files/State/StateManager.s: src/Source_Files/State/StateManager.cpp.s

.PHONY : src/Source_Files/State/StateManager.s

# target to generate assembly for a file
src/Source_Files/State/StateManager.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/State/StateManager.cpp.s
.PHONY : src/Source_Files/State/StateManager.cpp.s

src/Source_Files/Util/InputHandle.o: src/Source_Files/Util/InputHandle.cpp.o

.PHONY : src/Source_Files/Util/InputHandle.o

# target to build an object file
src/Source_Files/Util/InputHandle.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Util/InputHandle.cpp.o
.PHONY : src/Source_Files/Util/InputHandle.cpp.o

src/Source_Files/Util/InputHandle.i: src/Source_Files/Util/InputHandle.cpp.i

.PHONY : src/Source_Files/Util/InputHandle.i

# target to preprocess a source file
src/Source_Files/Util/InputHandle.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Util/InputHandle.cpp.i
.PHONY : src/Source_Files/Util/InputHandle.cpp.i

src/Source_Files/Util/InputHandle.s: src/Source_Files/Util/InputHandle.cpp.s

.PHONY : src/Source_Files/Util/InputHandle.s

# target to generate assembly for a file
src/Source_Files/Util/InputHandle.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Util/InputHandle.cpp.s
.PHONY : src/Source_Files/Util/InputHandle.cpp.s

src/Source_Files/Util/SFMLHelpers.o: src/Source_Files/Util/SFMLHelpers.cpp.o

.PHONY : src/Source_Files/Util/SFMLHelpers.o

# target to build an object file
src/Source_Files/Util/SFMLHelpers.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Util/SFMLHelpers.cpp.o
.PHONY : src/Source_Files/Util/SFMLHelpers.cpp.o

src/Source_Files/Util/SFMLHelpers.i: src/Source_Files/Util/SFMLHelpers.cpp.i

.PHONY : src/Source_Files/Util/SFMLHelpers.i

# target to preprocess a source file
src/Source_Files/Util/SFMLHelpers.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Util/SFMLHelpers.cpp.i
.PHONY : src/Source_Files/Util/SFMLHelpers.cpp.i

src/Source_Files/Util/SFMLHelpers.s: src/Source_Files/Util/SFMLHelpers.cpp.s

.PHONY : src/Source_Files/Util/SFMLHelpers.s

# target to generate assembly for a file
src/Source_Files/Util/SFMLHelpers.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/Util/SFMLHelpers.cpp.s
.PHONY : src/Source_Files/Util/SFMLHelpers.cpp.s

src/Source_Files/include.o: src/Source_Files/include.cpp.o

.PHONY : src/Source_Files/include.o

# target to build an object file
src/Source_Files/include.cpp.o:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/include.cpp.o
.PHONY : src/Source_Files/include.cpp.o

src/Source_Files/include.i: src/Source_Files/include.cpp.i

.PHONY : src/Source_Files/include.i

# target to preprocess a source file
src/Source_Files/include.cpp.i:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/include.cpp.i
.PHONY : src/Source_Files/include.cpp.i

src/Source_Files/include.s: src/Source_Files/include.cpp.s

.PHONY : src/Source_Files/include.s

# target to generate assembly for a file
src/Source_Files/include.cpp.s:
	$(MAKE) -f CMakeFiles/GameEngine2020.dir/build.make CMakeFiles/GameEngine2020.dir/src/Source_Files/include.cpp.s
.PHONY : src/Source_Files/include.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... GameEngine2020"
	@echo "... src/Source_Files/Actor/Actor.o"
	@echo "... src/Source_Files/Actor/Actor.i"
	@echo "... src/Source_Files/Actor/Actor.s"
	@echo "... src/Source_Files/Actor/Camera.o"
	@echo "... src/Source_Files/Actor/Camera.i"
	@echo "... src/Source_Files/Actor/Camera.s"
	@echo "... src/Source_Files/Actor/Player.o"
	@echo "... src/Source_Files/Actor/Player.i"
	@echo "... src/Source_Files/Actor/Player.s"
	@echo "... src/Source_Files/Behavior/ActionState/ActionStateMap.o"
	@echo "... src/Source_Files/Behavior/ActionState/ActionStateMap.i"
	@echo "... src/Source_Files/Behavior/ActionState/ActionStateMap.s"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerAirborneState.o"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerAirborneState.i"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerAirborneState.s"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerIdleState.o"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerIdleState.i"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerIdleState.s"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerJumpState.o"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerJumpState.i"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerJumpState.s"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerMoveState.o"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerMoveState.i"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerMoveState.s"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerRunState.o"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerRunState.i"
	@echo "... src/Source_Files/Behavior/ActionState/PlayerRunState.s"
	@echo "... src/Source_Files/Behavior/Animator.o"
	@echo "... src/Source_Files/Behavior/Animator.i"
	@echo "... src/Source_Files/Behavior/Animator.s"
	@echo "... src/Source_Files/Behavior/Behavior.o"
	@echo "... src/Source_Files/Behavior/Behavior.i"
	@echo "... src/Source_Files/Behavior/Behavior.s"
	@echo "... src/Source_Files/Behavior/GameTransform.o"
	@echo "... src/Source_Files/Behavior/GameTransform.i"
	@echo "... src/Source_Files/Behavior/GameTransform.s"
	@echo "... src/Source_Files/Behavior/PhysEventHandler.o"
	@echo "... src/Source_Files/Behavior/PhysEventHandler.i"
	@echo "... src/Source_Files/Behavior/PhysEventHandler.s"
	@echo "... src/Source_Files/GUI/Button.o"
	@echo "... src/Source_Files/GUI/Button.i"
	@echo "... src/Source_Files/GUI/Button.s"
	@echo "... src/Source_Files/GUI/MenuButton.o"
	@echo "... src/Source_Files/GUI/MenuButton.i"
	@echo "... src/Source_Files/GUI/MenuButton.s"
	@echo "... src/Source_Files/GUI/Widget.o"
	@echo "... src/Source_Files/GUI/Widget.i"
	@echo "... src/Source_Files/GUI/Widget.s"
	@echo "... src/Source_Files/GameEngine2020.o"
	@echo "... src/Source_Files/GameEngine2020.i"
	@echo "... src/Source_Files/GameEngine2020.s"
	@echo "... src/Source_Files/Graphics/Animation.o"
	@echo "... src/Source_Files/Graphics/Animation.i"
	@echo "... src/Source_Files/Graphics/Animation.s"
	@echo "... src/Source_Files/Graphics/Renderer.o"
	@echo "... src/Source_Files/Graphics/Renderer.i"
	@echo "... src/Source_Files/Graphics/Renderer.s"
	@echo "... src/Source_Files/Level/Level.o"
	@echo "... src/Source_Files/Level/Level.i"
	@echo "... src/Source_Files/Level/Level.s"
	@echo "... src/Source_Files/Physics/Bodies/PhysicsBody.o"
	@echo "... src/Source_Files/Physics/Bodies/PhysicsBody.i"
	@echo "... src/Source_Files/Physics/Bodies/PhysicsBody.s"
	@echo "... src/Source_Files/Physics/ColPair.o"
	@echo "... src/Source_Files/Physics/ColPair.i"
	@echo "... src/Source_Files/Physics/ColPair.s"
	@echo "... src/Source_Files/Physics/CollisionEvent.o"
	@echo "... src/Source_Files/Physics/CollisionEvent.i"
	@echo "... src/Source_Files/Physics/CollisionEvent.s"
	@echo "... src/Source_Files/Physics/PhysMath.o"
	@echo "... src/Source_Files/Physics/PhysMath.i"
	@echo "... src/Source_Files/Physics/PhysMath.s"
	@echo "... src/Source_Files/Physics/PhysicsEngine.o"
	@echo "... src/Source_Files/Physics/PhysicsEngine.i"
	@echo "... src/Source_Files/Physics/PhysicsEngine.s"
	@echo "... src/Source_Files/Physics/SweepAndPrune.o"
	@echo "... src/Source_Files/Physics/SweepAndPrune.i"
	@echo "... src/Source_Files/Physics/SweepAndPrune.s"
	@echo "... src/Source_Files/Space2D/AffineMatrix.o"
	@echo "... src/Source_Files/Space2D/AffineMatrix.i"
	@echo "... src/Source_Files/Space2D/AffineMatrix.s"
	@echo "... src/Source_Files/Space2D/AngularType.o"
	@echo "... src/Source_Files/Space2D/AngularType.i"
	@echo "... src/Source_Files/Space2D/AngularType.s"
	@echo "... src/Source_Files/Space2D/Dimension2.o"
	@echo "... src/Source_Files/Space2D/Dimension2.i"
	@echo "... src/Source_Files/Space2D/Dimension2.s"
	@echo "... src/Source_Files/Space2D/NormalizedVec2.o"
	@echo "... src/Source_Files/Space2D/NormalizedVec2.i"
	@echo "... src/Source_Files/Space2D/NormalizedVec2.s"
	@echo "... src/Source_Files/Space2D/Point2.o"
	@echo "... src/Source_Files/Space2D/Point2.i"
	@echo "... src/Source_Files/Space2D/Point2.s"
	@echo "... src/Source_Files/Space2D/Poly2.o"
	@echo "... src/Source_Files/Space2D/Poly2.i"
	@echo "... src/Source_Files/Space2D/Poly2.s"
	@echo "... src/Source_Files/Space2D/Rect2.o"
	@echo "... src/Source_Files/Space2D/Rect2.i"
	@echo "... src/Source_Files/Space2D/Rect2.s"
	@echo "... src/Source_Files/Space2D/Vec2.o"
	@echo "... src/Source_Files/Space2D/Vec2.i"
	@echo "... src/Source_Files/Space2D/Vec2.s"
	@echo "... src/Source_Files/State/GameState.o"
	@echo "... src/Source_Files/State/GameState.i"
	@echo "... src/Source_Files/State/GameState.s"
	@echo "... src/Source_Files/State/MenuState.o"
	@echo "... src/Source_Files/State/MenuState.i"
	@echo "... src/Source_Files/State/MenuState.s"
	@echo "... src/Source_Files/State/State.o"
	@echo "... src/Source_Files/State/State.i"
	@echo "... src/Source_Files/State/State.s"
	@echo "... src/Source_Files/State/StateManager.o"
	@echo "... src/Source_Files/State/StateManager.i"
	@echo "... src/Source_Files/State/StateManager.s"
	@echo "... src/Source_Files/Util/InputHandle.o"
	@echo "... src/Source_Files/Util/InputHandle.i"
	@echo "... src/Source_Files/Util/InputHandle.s"
	@echo "... src/Source_Files/Util/SFMLHelpers.o"
	@echo "... src/Source_Files/Util/SFMLHelpers.i"
	@echo "... src/Source_Files/Util/SFMLHelpers.s"
	@echo "... src/Source_Files/include.o"
	@echo "... src/Source_Files/include.i"
	@echo "... src/Source_Files/include.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

